### ISSUE TITLE
Erro quando existem mudanças na pagina do Receita Federal

### ISSUE THREAD

**Issue by Agapito78** [edigomes/download-nfe-sefaz#1]
Aparentemente o site do governo mudou a tag abaixo, removeu o atributo styles. O codigo abaixo nao estava conseguindo pegar o conteudo de 'src'

` preg_match('~<img id=\"ctl00_ContentPlaceHolder1_imgCaptcha\" src=\"(.*)\"  style~', $html, $_captcha);`
Fiz um ajuste e voltou a funcionar:
` preg_match('~<img id=\"ctl00_ContentPlaceHolder1_imgCaptcha\" src=\"(.*)\" ~', $html, $_captcha);`

**Comment by edigomes** [comment]
Valeu, estou concluindo uns commits para tudo funcionar 100% novamente, se puder mandar um pull request serial ótimo!

**Comment by edigomes** [comment]
Corrigido, obrigado pela contribuição!
